services:
  metabase:
    image: stephaneturquay/metabase-arm64:latest
    container_name: metabase-dattabot
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=5432
      - MB_DB_USER=dattabot
      - MB_DB_PASS=dattabot
      - MB_DB_HOST=metabase-app-db
    ports:
      - "3000:3000"
    depends_on:
      - metabase-app-db

  metabase-app-db:
    image: postgres:13-alpine
    container_name: metabase-postgres-dattabot
    environment:
      POSTGRES_USER: dattabot
      POSTGRES_PASSWORD: dattabot
      POSTGRES_DB: metabase
    volumes:
      - ./metabase_postgres_data:/var/lib/postgresql/data

  data-warehouse:
    image: postgres:13-alpine
    container_name: dattabot-postgres
    environment:
      POSTGRES_USER: dattabot
      POSTGRES_PASSWORD: dattabot
      POSTGRES_DB: data_warehouse
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
