services:
  metabase:
    image: stephaneturquay/metabase-arm64:latest
    container_name: dattabot-metabase
    ports:
      - "3000:3000"

  data-warehouse:
    image: postgres:13-alpine
    container_name: dattabot-postgres
    environment:
      POSTGRES_USER: dattabot
      POSTGRES_PASSWORD: dattabot
      POSTGRES_DB: data_warehouse
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
